using EchoLifestyle.Domain.Inventory;

namespace EchoLifestyle.Application.Inventory;

/// <summary>
/// One product's stock in one warehouse, summed across its batches.
/// </summary>
public class StockOnHandItem
{
    public long ProductVariantId { get; set; }

    public string Sku { get; set; } = string.Empty;

    public string ProductName { get; set; } = string.Empty;

    public string VariantName { get; set; } = string.Empty;

    public string BrandName { get; set; } = string.Empty;

    public long WarehouseId { get; set; }

    public string WarehouseName { get; set; } = string.Empty;

    public decimal QuantityOnHand { get; set; }

    public decimal QuantityReserved { get; set; }

    /// <summary>What can actually be promised to a customer.</summary>
    public decimal QuantityAvailable => QuantityOnHand - QuantityReserved;

    public int BatchCount { get; set; }

    /// <summary>Sum of quantity times each batch's own landed cost.</summary>
    public decimal StockValue { get; set; }

    /// <summary>
    /// Value divided by quantity. The weighted average is a view over
    /// batch-level actual costs, never the other way round - so it can be shown
    /// without anything being valued at a number nobody paid.
    /// </summary>
    public decimal? AverageUnitCost =>
        QuantityOnHand == 0m ? null : decimal.Round(StockValue / QuantityOnHand, 4);

    /// <summary>Drives the near-expiry warning on the row.</summary>
    public DateOnly? EarliestExpiry { get; set; }
}

/// <summary>One batch of one product sitting in one warehouse.</summary>
public class StockBatchItem
{
    public long StockBatchId { get; set; }

    public string BatchNumber { get; set; } = string.Empty;

    public bool IsAutoGenerated { get; set; }

    public string WarehouseName { get; set; } = string.Empty;

    public decimal QuantityOnHand { get; set; }

    public decimal QuantityReserved { get; set; }

    public decimal LandedUnitCost { get; set; }

    public decimal Value => decimal.Round(QuantityOnHand * LandedUnitCost, 4);

    public DateOnly ReceivedDate { get; set; }

    public DateOnly? ExpiryDate { get; set; }

    public string? SupplierName { get; set; }
}

public class StockMovementItem
{
    public long Id { get; set; }

    public DateOnly BusinessDate { get; set; }

    public DateTime OccurredAtUtc { get; set; }

    public string Sku { get; set; } = string.Empty;

    public string ProductName { get; set; } = string.Empty;

    public string VariantName { get; set; } = string.Empty;

    public string WarehouseName { get; set; } = string.Empty;

    public string BatchNumber { get; set; } = string.Empty;

    public bool BatchWasGenerated { get; set; }

    public StockMovementType MovementType { get; set; }

    public decimal QuantityChange { get; set; }

    public decimal UnitCost { get; set; }

    public decimal ValueChange { get; set; }

    public StockDocumentType DocumentType { get; set; }

    public long DocumentId { get; set; }

    public string DocumentNumber { get; set; } = string.Empty;

    public string? Notes { get; set; }
}

public class ExpiringBatchItem
{
    public long StockBatchId { get; set; }

    public long ProductVariantId { get; set; }

    public string Sku { get; set; } = string.Empty;

    public string ProductName { get; set; } = string.Empty;

    public string VariantName { get; set; } = string.Empty;

    public string BatchNumber { get; set; } = string.Empty;

    public string WarehouseName { get; set; } = string.Empty;

    public DateOnly ExpiryDate { get; set; }

    public int DaysRemaining { get; set; }

    public decimal QuantityOnHand { get; set; }

    public decimal LandedUnitCost { get; set; }

    public decimal ValueAtRisk => decimal.Round(QuantityOnHand * LandedUnitCost, 4);

    /// <summary>Already past its date and still on the shelf.</summary>
    public bool HasExpired => DaysRemaining < 0;
}

/// <summary>What a rebuild found and put right.</summary>
public class BalanceRebuildSummary
{
    public int Checked { get; set; }

    public int Corrected { get; set; }

    public int Created { get; set; }

    public int Zeroed { get; set; }

    public List<BalanceDiscrepancy> Discrepancies { get; set; } = [];

    public bool FoundNothingWrong => Corrected == 0 && Created == 0 && Zeroed == 0;

    public string Describe() =>
        FoundNothingWrong
            ? $"Checked {Checked} balance(s). Every one already matched the ledger."
            : $"Checked {Checked} balance(s): {Corrected} corrected, {Created} created, {Zeroed} zeroed.";
}

public class BalanceDiscrepancy
{
    public long ProductVariantId { get; set; }

    public string Sku { get; set; } = string.Empty;

    public long StockBatchId { get; set; }

    public decimal Was { get; set; }

    public decimal Now { get; set; }
}
