using EchoLifestyle.Domain.Catalog;
using EchoLifestyle.Domain.Common;

namespace EchoLifestyle.Domain.Inventory;

/// <summary>
/// A lot of one variant, received together and sharing an expiry date and a
/// landed cost.
///
/// Deliberately not tied to a warehouse: a batch is a physical lot, and where
/// that lot currently sits is a question for the ledger. Modelling location
/// here would mean inventing a second batch the first time stock moved between
/// locations, and its expiry date would then be duplicated in two places.
/// </summary>
public class StockBatch : AuditableEntity
{
    public long ProductVariantId { get; set; }

    public ProductVariant? ProductVariant { get; set; }

    /// <summary>
    /// The supplier's batch number, or a generated one for products nobody
    /// tracks batches on. Unique per variant.
    /// </summary>
    public string BatchNumber { get; set; } = string.Empty;

    /// <summary>
    /// True when the number was generated rather than typed. The UI hides these
    /// so that "light batch entry" really does mean the person never sees a
    /// batch number they did not ask for.
    /// </summary>
    public bool IsAutoGenerated { get; set; }

    public DateOnly? ExpiryDate { get; set; }

    public DateOnly? ManufactureDate { get; set; }

    public DateOnly ReceivedDate { get; set; }

    /// <summary>
    /// Unit cost including its share of freight, duty and clearing, frozen at
    /// receipt. This is what the ledger records and what margin is measured
    /// against - not a blended average, so "this cost 320 because it came from
    /// the March shipment" is answerable.
    /// </summary>
    public decimal LandedUnitCost { get; set; }

    public long? SupplierId { get; set; }

    /// <summary>The receipt that created it, for tracing a recall back to a delivery.</summary>
    public long? GoodsReceiptId { get; set; }

    public ICollection<StockLedgerEntry> LedgerEntries { get; set; } = new List<StockLedgerEntry>();
}
