using EchoLifestyle.Domain.Inventory;

namespace EchoLifestyle.Application.Inventory.Adjustments;

/// <summary>
/// One screen of adjusting: why, where, and which batches move.
/// </summary>
public class SubmitAdjustmentRequest
{
    public long WarehouseId { get; set; }

    public long BranchId { get; set; }

    /// <summary>Defaults to today's business date when not given.</summary>
    public DateOnly? AdjustmentDate { get; set; }

    public StockAdjustmentReason Reason { get; set; }

    /// <summary>
    /// Required, and the only free text on the document that matters. "Damaged"
    /// is a category; "carton crushed under the shelf on the 3rd" is an
    /// explanation somebody can still use in a year.
    /// </summary>
    public string ReasonNotes { get; set; } = string.Empty;

    public IReadOnlyList<AdjustmentLineInput> Lines { get; set; } = [];
}

public class AdjustmentLineInput
{
    public long ProductVariantId { get; set; }

    /// <summary>
    /// Required. Stock leaving has a cost, and cost lives on the batch - taking
    /// stock out "at the average" would value the loss at a figure nobody paid.
    /// </summary>
    public long StockBatchId { get; set; }

    /// <summary>Signed. The header's reason constrains which signs are allowed.</summary>
    public decimal QuantityChange { get; set; }

    public string? Notes { get; set; }
}

public class StockAdjustmentListItem
{
    public long Id { get; set; }

    public string Number { get; set; } = string.Empty;

    public string WarehouseName { get; set; } = string.Empty;

    public DateOnly AdjustmentDate { get; set; }

    public StockAdjustmentReason Reason { get; set; }

    public StockAdjustmentStatus Status { get; set; }

    public string ReasonNotes { get; set; } = string.Empty;

    public int LineCount { get; set; }

    /// <summary>Signed net units. Usually negative - most adjustments are losses.</summary>
    public decimal TotalQuantityChange { get; set; }

    /// <summary>
    /// Zero until the document posts: cost is copied onto the lines at posting,
    /// so a pending adjustment has no value yet to report.
    /// </summary>
    public decimal TotalValueChange { get; set; }

    public bool WasSelfApproved { get; set; }
}

public class StockAdjustmentDetail
{
    public long Id { get; set; }

    public string Number { get; set; } = string.Empty;

    public long WarehouseId { get; set; }

    public string WarehouseName { get; set; } = string.Empty;

    public DateOnly AdjustmentDate { get; set; }

    public StockAdjustmentReason Reason { get; set; }

    public StockAdjustmentStatus Status { get; set; }

    public string ReasonNotes { get; set; } = string.Empty;

    public string? DecisionNotes { get; set; }

    public DateTime? ApprovedAtUtc { get; set; }

    public DateTime? PostedAtUtc { get; set; }

    public bool WasSelfApproved { get; set; }

    public IReadOnlyList<StockAdjustmentLineDetail> Lines { get; set; } = [];

    public decimal TotalQuantityChange => Lines.Sum(l => l.QuantityChange);

    public decimal TotalValueChange => Lines.Sum(l => l.ValueChange);
}

public class StockAdjustmentLineDetail
{
    public long Id { get; set; }

    public long ProductVariantId { get; set; }

    public string Sku { get; set; } = string.Empty;

    public string ProductName { get; set; } = string.Empty;

    public string VariantName { get; set; } = string.Empty;

    public string BatchNumber { get; set; } = string.Empty;

    public bool BatchWasGenerated { get; set; }

    public DateOnly? ExpiryDate { get; set; }

    public decimal QuantityChange { get; set; }

    /// <summary>
    /// Zero while pending. The batch's landed cost is copied here at posting so
    /// that recosting the batch afterwards cannot rewrite what this loss was
    /// worth.
    /// </summary>
    public decimal UnitCost { get; set; }

    public decimal ValueChange { get; set; }

    public string? Notes { get; set; }
}

/// <summary>
/// A batch somebody can adjust: what is in it now, and what it cost.
///
/// Batches sitting at zero are included, because "found extra" needs somewhere
/// to put stock that came back and the only honest answer is the batch it left
/// from.
/// </summary>
public class AdjustableBatchItem
{
    public long StockBatchId { get; set; }

    public string BatchNumber { get; set; } = string.Empty;

    public bool IsAutoGenerated { get; set; }

    public DateOnly ReceivedDate { get; set; }

    public DateOnly? ExpiryDate { get; set; }

    public decimal QuantityOnHand { get; set; }

    public decimal LandedUnitCost { get; set; }

    public string? SupplierName { get; set; }

    /// <summary>
    /// "GRN-2609-0004 · 12 on hand · expires 3 Mar 2027" - enough to pick the
    /// right batch off a dropdown without opening another screen.
    /// </summary>
    public string Display
    {
        get
        {
            var label = IsAutoGenerated ? "Not tracked" : BatchNumber;
            var text = $"{label} · {QuantityOnHand:N0} on hand";

            return ExpiryDate is null
                ? text
                : $"{text} · expires {ExpiryDate.Value:d MMM yyyy}";
        }
    }
}
