using EchoLifestyle.Application.Common.Results;
using EchoLifestyle.Domain.Inventory;
using Microsoft.EntityFrameworkCore;

namespace EchoLifestyle.Application.Inventory.Counts;

/// <summary>Reading counts back.</summary>
public partial class StockCountService
{
    public async Task<PagedResult<StockCountListItem>> ListAsync(
        string? search,
        int skip,
        int take,
        string? sortColumn,
        bool sortDescending,
        StockCountStatus? status,
        CancellationToken cancellationToken = default)
    {
        var query = _db.StockCounts.AsNoTracking();

        var totalCount = await query.CountAsync(cancellationToken);

        if (status is not null)
        {
            query = query.Where(c => c.Status == status);
        }

        if (!string.IsNullOrWhiteSpace(search))
        {
            var term = search.Trim();
            query = query.Where(c =>
                EF.Functions.Like(c.Number, $"%{term}%")
                || (c.ScopeName != null && EF.Functions.Like(c.ScopeName, $"%{term}%"))
                || (c.Notes != null && EF.Functions.Like(c.Notes, $"%{term}%")));
        }

        var filteredCount = await query.CountAsync(cancellationToken);

        query = (sortColumn, sortDescending) switch
        {
            ("number", false) => query.OrderBy(c => c.Number),
            ("date", false) => query.OrderBy(c => c.CountDate).ThenBy(c => c.Number),
            ("date", true) => query.OrderByDescending(c => c.CountDate).ThenByDescending(c => c.Number),

            // Open counts first: one is either in progress or it is history, and
            // the one in progress is why somebody is on this screen.
            _ => query.OrderBy(c => c.Status == StockCountStatus.Counting ? 0 : 1)
                      .ThenByDescending(c => c.Number),
        };

        var rows = await query
            .Skip(skip)
            .Take(take)
            .Select(c => new StockCountListItem
            {
                Id = c.Id,
                Number = c.Number,
                WarehouseName = c.Warehouse!.Name,
                CountDate = c.CountDate,
                Scope = c.Scope,
                ScopeName = c.ScopeName,
                Status = c.Status,
                LineCount = c.Lines.Count,
                CountedCount = c.Lines.Count(l => l.CountedQuantity != null),
                VarianceCount = c.Lines.Count(l => l.CountedQuantity != null
                                                   && l.CountedQuantity != l.SystemQuantity),
                PostedAtUtc = c.PostedAtUtc,
            })
            .ToListAsync(cancellationToken);

        return new PagedResult<StockCountListItem>(rows, totalCount, filteredCount);
    }

    /// <summary>
    /// One count with its sheet.
    ///
    /// Each line carries both the snapshot and the live balance, so the review
    /// screen can point out anything that moved while the count was in progress.
    /// That is not an error - stock is allowed to move - but somebody about to
    /// post should see it.
    /// </summary>
    public async Task<StockCountDetail?> GetAsync(
        long id,
        CancellationToken cancellationToken = default)
    {
        var count = await _db.StockCounts
            .AsNoTracking()
            .Include(c => c.Warehouse)
            .FirstOrDefaultAsync(c => c.Id == id, cancellationToken);

        if (count is null)
        {
            return null;
        }

        // Hoisted to a plain local: the projection below is translated to SQL,
        // and a scalar is unambiguously a parameter where a property walk on a
        // captured entity is not.
        var warehouseId = count.WarehouseId;

        var lines = await _db.StockCountLines
            .AsNoTracking()
            .Where(l => l.StockCountId == id)
            .Select(l => new StockCountLineDetail
            {
                Id = l.Id,
                ProductVariantId = l.ProductVariantId,
                StockBatchId = l.StockBatchId,
                Sku = l.ProductVariant!.Sku,
                ProductName = l.ProductVariant.Product!.Name,
                VariantName = l.ProductVariant.VariantName,
                BrandName = l.ProductVariant.Product.Brand!.Name,
                BatchNumber = l.StockBatch!.BatchNumber,
                BatchWasGenerated = l.StockBatch.IsAutoGenerated,
                ExpiryDate = l.StockBatch.ExpiryDate,
                SystemQuantity = l.SystemQuantity,

                CurrentSystemQuantity = _db.StockBalances
                    .Where(b => b.StockBatchId == l.StockBatchId
                                && b.WarehouseId == warehouseId)
                    .Select(b => (decimal?)b.QuantityOnHand)
                    .FirstOrDefault() ?? 0m,

                CountedQuantity = l.CountedQuantity,
                LandedUnitCost = l.LandedUnitCost,
                Notes = l.Notes,
            })
            .ToListAsync(cancellationToken);

        return new StockCountDetail
        {
            Id = count.Id,
            Number = count.Number,
            WarehouseId = count.WarehouseId,
            WarehouseName = count.Warehouse?.Name ?? string.Empty,
            BranchId = count.BranchId,
            CountDate = count.CountDate,
            Scope = count.Scope,
            ScopeName = count.ScopeName,
            Status = count.Status,
            Notes = count.Notes,
            SnapshotAtUtc = count.SnapshotAtUtc,
            PostedAtUtc = count.PostedAtUtc,

            // Sorted the way a shelf is walked: by brand, then product, then the
            // batch that expires first.
            Lines = lines
                .OrderBy(l => l.BrandName)
                .ThenBy(l => l.ProductName)
                .ThenBy(l => l.VariantName)
                .ThenBy(l => l.ExpiryDate ?? DateOnly.MaxValue)
                .ToList(),
        };
    }

    /// <summary>The open count for a warehouse, if there is one.</summary>
    public Task<long?> FindOpenAsync(long warehouseId, CancellationToken cancellationToken = default) =>
        _db.StockCounts
            .AsNoTracking()
            .Where(c => c.WarehouseId == warehouseId && c.Status == StockCountStatus.Counting)
            .Select(c => (long?)c.Id)
            .FirstOrDefaultAsync(cancellationToken);

    public async Task<IReadOnlyList<CountScopeOption>> GetBrandOptionsAsync(
        CancellationToken cancellationToken = default) =>
        await _db.Brands
            .AsNoTracking()
            .Where(b => b.IsActive)
            .OrderBy(b => b.Name)
            .Select(b => new CountScopeOption { Id = b.Id, Name = b.Name })
            .ToListAsync(cancellationToken);

    public async Task<IReadOnlyList<CountScopeOption>> GetCategoryOptionsAsync(
        CancellationToken cancellationToken = default)
    {
        var rows = await _db.Categories
            .AsNoTracking()
            .Where(c => c.IsActive)
            .OrderBy(c => c.Path)
            .Select(c => new { c.Id, c.Name, c.Depth })
            .ToListAsync(cancellationToken);

        // Indented by depth so the tree is readable in a flat dropdown.
        return rows
            .Select(c => new CountScopeOption
            {
                Id = c.Id,
                Name = c.Depth == 0 ? c.Name : $"{new string(' ', c.Depth * 4)}{c.Name}",
            })
            .ToList();
    }
}
