using EchoLifestyle.Domain.Administration;
using EchoLifestyle.Domain.Catalog;
using EchoLifestyle.Domain.Inventory;
using EchoLifestyle.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;

namespace EchoLifestyle.IntegrationTests;

/// <summary>
/// The guarantees behind rule 1 - stock never moves without a ledger entry, and
/// the ledger is never rewritten.
///
/// These are the tests that most justify a real database. An append-only rule
/// enforced only by convention is a rule until the first person in a hurry; a
/// sign convention enforced only in C# is correct until the first fix-up
/// script.
/// </summary>
[Collection(DatabaseCollection.Name)]
public class StockLedgerConstraintsTests : IAsyncLifetime
{
    private readonly DatabaseFixture _fixture;

    private long _variantId;
    private long _warehouseId;
    private long _batchId;

    public StockLedgerConstraintsTests(DatabaseFixture fixture)
    {
        _fixture = fixture;
    }

    public async Task InitializeAsync()
    {
        await using var scope = _fixture.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<EchoDbContext>();

        var suffix = Guid.NewGuid().ToString("N")[..10];

        var company = new Company { Name = $"Ledger Test Co {suffix}" };
        var brand = new Brand { Name = $"Ledger brand {suffix}", Slug = $"ledger-brand-{suffix}" };
        var unit = new UnitOfMeasure { Code = $"L{suffix[..4]}", Name = "Ledger unit" };

        db.AddRange(company, brand, unit);
        await db.SaveChangesAsync();

        var warehouse = new Warehouse
        {
            CompanyId = company.Id,
            Code = $"LW{suffix[..6]}",
            Name = "Ledger warehouse",
        };

        var product = new Product
        {
            Code = $"LP-{suffix}",
            Name = $"Ledger product {suffix}",
            Slug = $"ledger-product-{suffix}",
            BrandId = brand.Id,
            UnitOfMeasureId = unit.Id,
        };

        db.AddRange(warehouse, product);
        await db.SaveChangesAsync();

        var variant = new ProductVariant
        {
            ProductId = product.Id,
            Sku = $"LSKU-{suffix}",
            VariantName = "Standard",
            IsDefault = true,
        };

        db.ProductVariants.Add(variant);
        await db.SaveChangesAsync();

        var batch = new StockBatch
        {
            ProductVariantId = variant.Id,
            BatchNumber = $"B-{suffix}",
            ReceivedDate = new DateOnly(2026, 9, 1),
            LandedUnitCost = 320m,
            IsAutoGenerated = true,
        };

        db.StockBatches.Add(batch);
        await db.SaveChangesAsync();

        _variantId = variant.Id;
        _warehouseId = warehouse.Id;
        _batchId = batch.Id;
    }

    public Task DisposeAsync() => Task.CompletedTask;

    /// <summary>
    /// Deliberately far outside the range real documents will ever reach.
    ///
    /// These rows reference no actual receipt, and a document id of 1 would make
    /// them look like they belonged to the first real one - which is exactly how
    /// a query for "the movements of receipt 1" ends up with somebody else's
    /// test data in it.
    /// </summary>
    private const long SyntheticDocumentId = 999_000_001;

    private StockLedgerEntry Entry(
        StockMovementType type,
        decimal quantity,
        string documentNumber = "TEST-001") => new()
    {
        ProductVariantId = _variantId,
        WarehouseId = _warehouseId,
        StockBatchId = _batchId,
        MovementType = type,
        QuantityChange = quantity,
        UnitCost = 320m,
        ValueChange = quantity * 320m,
        DocumentType = StockDocumentType.GoodsReceipt,
        DocumentId = SyntheticDocumentId,
        DocumentNumber = documentNumber,
        OccurredAtUtc = DateTime.UtcNow,
        BusinessDate = new DateOnly(2026, 9, 6),
    };

    [Fact]
    public async Task A_ledger_entry_cannot_be_changed_once_written()
    {
        await using var scope = _fixture.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<EchoDbContext>();

        var entry = Entry(StockMovementType.Receipt, 10m);
        db.StockLedger.Add(entry);
        await db.SaveChangesAsync();

        entry.QuantityChange = 999m;

        // Editing history would change every balance derived from this row with
        // nothing to show that it happened.
        var ex = await Assert.ThrowsAsync<InvalidOperationException>(() => db.SaveChangesAsync());
        Assert.Contains("append-only", ex.Message, StringComparison.OrdinalIgnoreCase);
        Assert.Contains("reversing entry", ex.Message, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task A_ledger_entry_cannot_be_deleted()
    {
        await using var scope = _fixture.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<EchoDbContext>();

        var entry = Entry(StockMovementType.Receipt, 5m);
        db.StockLedger.Add(entry);
        await db.SaveChangesAsync();

        db.StockLedger.Remove(entry);

        var ex = await Assert.ThrowsAsync<InvalidOperationException>(() => db.SaveChangesAsync());
        Assert.Contains("append-only", ex.Message, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public async Task A_correction_is_a_reversing_entry_and_both_rows_survive()
    {
        await using var scope = _fixture.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<EchoDbContext>();

        var document = $"REV-{Guid.NewGuid().ToString("N")[..8]}";

        db.StockLedger.Add(Entry(StockMovementType.Receipt, 12m, document));
        await db.SaveChangesAsync();

        db.StockLedger.Add(Entry(StockMovementType.AdjustmentOut, -12m, document));
        await db.SaveChangesAsync();

        var rows = await db.StockLedger
            .Where(e => e.DocumentNumber == document)
            .ToListAsync();

        // Both the mistake and its correction stay visible. That is the point:
        // the ledger says what happened, not what somebody wishes had happened.
        Assert.Equal(2, rows.Count);
        Assert.Equal(0m, rows.Sum(r => r.QuantityChange));
    }

    [Theory]
    [InlineData(StockMovementType.Receipt, -1)]
    [InlineData(StockMovementType.AdjustmentIn, -1)]
    [InlineData(StockMovementType.ReturnFromCustomer, -1)]
    [InlineData(StockMovementType.TransferIn, -1)]
    [InlineData(StockMovementType.OpeningBalance, -1)]
    public async Task An_inbound_movement_cannot_carry_a_negative_quantity(
        StockMovementType type,
        decimal quantity)
    {
        await using var scope = _fixture.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<EchoDbContext>();

        db.StockLedger.Add(Entry(type, quantity));

        // The check constraint, not the service. Nothing outside the
        // application - a script, a DBA, a future job - can write a sign error
        // that would silently corrupt every balance built from this row.
        await Assert.ThrowsAsync<DbUpdateException>(() => db.SaveChangesAsync());
    }

    [Theory]
    [InlineData(StockMovementType.Issue, 1)]
    [InlineData(StockMovementType.AdjustmentOut, 1)]
    [InlineData(StockMovementType.ReturnToSupplier, 1)]
    [InlineData(StockMovementType.TransferOut, 1)]
    [InlineData(StockMovementType.WriteOff, 1)]
    public async Task An_outbound_movement_cannot_carry_a_positive_quantity(
        StockMovementType type,
        decimal quantity)
    {
        await using var scope = _fixture.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<EchoDbContext>();

        db.StockLedger.Add(Entry(type, quantity));

        await Assert.ThrowsAsync<DbUpdateException>(() => db.SaveChangesAsync());
    }

    [Fact]
    public async Task A_movement_of_nothing_is_refused()
    {
        await using var scope = _fixture.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<EchoDbContext>();

        db.StockLedger.Add(Entry(StockMovementType.Receipt, 0m));

        // Zero-quantity rows would fill the ledger with entries that mean
        // nothing and hide whatever bug produced them.
        await Assert.ThrowsAsync<DbUpdateException>(() => db.SaveChangesAsync());
    }

    [Fact]
    public async Task The_domain_and_the_database_agree_on_which_movements_are_inbound()
    {
        await using var scope = _fixture.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<EchoDbContext>();

        // Two statements of the same rule - one in C#, one as a check
        // constraint - so this asserts they have not drifted apart.
        foreach (var type in Enum.GetValues<StockMovementType>())
        {
            var quantity = StockLedgerEntry.IsInbound(type) ? 3m : -3m;

            db.StockLedger.Add(Entry(type, quantity, $"AGREE-{(int)type}"));
        }

        await db.SaveChangesAsync();

        Assert.Equal(
            Enum.GetValues<StockMovementType>().Length,
            await db.StockLedger.CountAsync(e => e.DocumentNumber.StartsWith("AGREE-")));
    }

    [Fact]
    public async Task A_batch_number_is_unique_within_a_variant()
    {
        await using var scope = _fixture.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<EchoDbContext>();

        var number = $"DUP-{Guid.NewGuid().ToString("N")[..8]}";

        db.StockBatches.Add(new StockBatch
        {
            ProductVariantId = _variantId,
            BatchNumber = number,
            ReceivedDate = new DateOnly(2026, 9, 1),
            LandedUnitCost = 100m,
        });
        await db.SaveChangesAsync();

        db.StockBatches.Add(new StockBatch
        {
            ProductVariantId = _variantId,
            BatchNumber = number,
            ReceivedDate = new DateOnly(2026, 9, 2),
            LandedUnitCost = 110m,
        });

        // Two batches sharing a number would make a recall ambiguous.
        await Assert.ThrowsAsync<DbUpdateException>(() => db.SaveChangesAsync());
    }

    [Fact]
    public async Task One_balance_row_per_batch_per_warehouse()
    {
        await using var scope = _fixture.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<EchoDbContext>();

        db.StockBalances.Add(new StockBalance
        {
            ProductVariantId = _variantId,
            WarehouseId = _warehouseId,
            StockBatchId = _batchId,
            QuantityOnHand = 10m,
        });
        await db.SaveChangesAsync();

        db.StockBalances.Add(new StockBalance
        {
            ProductVariantId = _variantId,
            WarehouseId = _warehouseId,
            StockBatchId = _batchId,
            QuantityOnHand = 4m,
        });

        // Two rows would make the answer to "how many do we have" depend on
        // which one a query happened to find first.
        await Assert.ThrowsAsync<DbUpdateException>(() => db.SaveChangesAsync());
    }

    [Fact]
    public async Task A_balance_cannot_reserve_a_negative_quantity()
    {
        await using var scope = _fixture.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<EchoDbContext>();

        var batch = new StockBatch
        {
            ProductVariantId = _variantId,
            BatchNumber = $"NEG-{Guid.NewGuid().ToString("N")[..8]}",
            ReceivedDate = new DateOnly(2026, 9, 1),
            LandedUnitCost = 100m,
        };
        db.StockBatches.Add(batch);
        await db.SaveChangesAsync();

        db.StockBalances.Add(new StockBalance
        {
            ProductVariantId = _variantId,
            WarehouseId = _warehouseId,
            StockBatchId = batch.Id,
            QuantityOnHand = 5m,
            QuantityReserved = -1m,
        });

        // Negative stock is a branch policy decision. A negative reservation is
        // always a bug.
        await Assert.ThrowsAsync<DbUpdateException>(() => db.SaveChangesAsync());
    }

    [Fact]
    public async Task A_balance_is_the_sum_of_its_ledger_entries()
    {
        await using var scope = _fixture.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<EchoDbContext>();

        var document = $"SUM-{Guid.NewGuid().ToString("N")[..8]}";

        db.StockLedger.AddRange(
            Entry(StockMovementType.Receipt, 20m, document),
            Entry(StockMovementType.Issue, -6m, document),
            Entry(StockMovementType.ReturnFromCustomer, 2m, document),
            Entry(StockMovementType.WriteOff, -1m, document));

        await db.SaveChangesAsync();

        var balance = await db.StockLedger
            .Where(e => e.DocumentNumber == document)
            .SumAsync(e => e.QuantityChange);

        // Signed quantities are what make this a plain SUM. A separate
        // direction column would put a conditional in every balance query, and
        // one of them would eventually get it wrong.
        Assert.Equal(15m, balance);
    }
}
